version: "3"
services: 
  es01:
    build:
      context: ../elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch01
    ports:
      - "9200:9200"
    volumes:
      - ../elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=node01
      # JVMのメモリを指定する。指定しないとメモリが足らなかった。。。
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    expose:
      - "9200"
  cerebro:
    image: yannart/cerebro:latest
    container_name: cerebro
    ports:
      - "9001:9000"
    restart: always
