version: "3"
services: 
  es01:
    build:
      context: ../elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch01
    ports:
      - "9200:9200"
    volumes:
      - ../elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=node01
      # JVMのメモリを指定する。指定しないとメモリが足らなかった。。。
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    expose:
      - "9200"
  cerebro:
    image: yannart/cerebro:latest
    container_name: cerebro
    ports:
      - "9001:9000"
    restart: always
  db:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ../mysql/db/data:/var/lib/mysql
      - ../mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: searchapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
  redis:
    image: "redis:latest"
    ports: 
      - "6379:6379"
    volumes:
      - ../redis/data:/data
